### ISSUE TITLE
Build Error on Android build 

### ISSUE THREAD

**Issue by PistolStarKei** [0maru/twitter_login#1]
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (3, 28): Conflicting import, imported name 'NonNull' is ambiguous
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (5, 28): Conflicting import, imported name 'NonNull' is ambiguous
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (75, 3): 'onNewIntent' overrides nothing
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (94, 3): 'onAttachedToActivity' overrides nothing
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (96, 36): Type mismatch: inferred type is TwitterLoginPlugin but PluginRegistry.NewIntentListener was expected
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (99, 3): 'onDetachedFromActivity' overrides nothing
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (100, 54): Type mismatch: inferred type is TwitterLoginPlugin but PluginRegistry.NewIntentListener was expected
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (104, 3): 'onDetachedFromActivityForConfigChanges' overrides nothing
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (105, 54): Type mismatch: inferred type is TwitterLoginPlugin but PluginRegistry.NewIntentListener was expected
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (109, 3): 'onReattachedToActivityForConfigChanges' overrides nothing
e: /Applications/flutter/.pub-cache/hosted/pub.dartlang.org/twitter_login-0.0.1/android/src/main/kotlin/com/maru/twitter_login/TwitterLoginPlugin.kt: (111, 36): Type mismatch: inferred type is TwitterLoginPlugin but PluginRegistry.NewIntentListener was expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':twitter_login:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by 0maru** [comment]
Sorry for the inconvenience, I  fixed the bug.
Thank you for opening the first issue :)

**Comment by HTsuruo** [comment]
sorry, It's my fault.. 
Probably, the problem is platform channel.
it's work well when change to `stable` channel.
Thank you.
