### ISSUE TITLE
[urlScheme] iOS14 - Not routed back to application

### ISSUE THREAD

**Issue by bounty1342** [0maru/twitter_login#10]
Hi,

I can't make it work on iOS 14. Spent literally hours, trying different combination for the urlScheme with no success.
After the login, the URLScheme don't come back to application and result in user cancel.

https://developer.twitter.com/ :
![image](https://user-images.githubusercontent.com/6307253/99491290-c4819c00-296b-11eb-9542-9880cfb5f380.png)

![image](https://user-images.githubusercontent.com/6307253/99491693-7caf4480-296c-11eb-8cb0-009c56b9cbf9.png)

```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLName</key>
    <string>app.flutter.twitter.login.schemes</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>easivio</string>
    </array>
  </dict>
</array>
```

![image](https://user-images.githubusercontent.com/6307253/99491725-918bd800-296c-11eb-856a-4df596fae429.png)

Please help,
Regards

**Comment by bounty1342** [comment]
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
     <key>CFBundleIdentifier</key>
     <string>easivio</string>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>easivio</string>
    </array>
  </dict>
</array>
```

This will work !
Otherwise the Url is not correct, I think you should do a more complete example on this as it's not trivial those Info.plist for non ios dev.

Regards,

**Comment by 0maru** [comment]
Added to [README.md](https://github.com/0maru/twitter_login/blob/master/README.md#add-urlscheme) about info.plist.
Please let me know if there are any problems.

**Comment by 0maru** [comment]
@bounty1342 
Added to [README.md](https://github.com/0maru/twitter_login/blob/master/README.md#add-urlscheme) about info.plist.
Please let me know if there are any problems.
