### ISSUE TITLE
Unhandled Exception: PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)

### ISSUE THREAD

**Issue by samir-concetto** [0maru/twitter_login#100]
the url :- https://api.twitter.com/oauth/request_token  is forbidden or not found in this plugin

**Comment by 0maru** [comment]
https://api.twitter.com/oauth/request_token is exists.
https://github.com/0maru/twitter_login/blob/master/lib/schemes/request_token.dart#L39:L67 

Please check your api key and api secret key.

**Comment by joao10martins** [comment]
I have the same issue. My api key & secret are good because they've been user in another lib before.
`AuthResult`, `RequestToken` fields on `twitter_login.dart` are for example not recognisable by AS.

**Comment by 0maru** [comment]
@samir-concetto @joao10martins 
I was able to log in with v4.2.2.
You might try both login() and loginV2() method to get it to work.
If it doesn't work, please run the example project of this plugin and let me know the result.

**Comment by joao10martins** [comment]
It worked for me after I MANUALLY imported `auth_result.dart` & `request_token.dart` into the `twitter_login` class

**Comment by samir-concetto** [comment]
> It worked for me after I MANUALLY imported `auth_result.dart` & `request_token.dart` into the `twitter_login` class

**Comment by samir-concetto** [comment]
> It worked for me after I MANUALLY imported `auth_result.dart` & `request_token.dart` into the `twitter_login` class

thanks it's working fine now

**Comment by jaibyron** [comment]
@0maru - I was unable to run the example project and get the same error : 

PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)

Can you please advise?
