### ISSUE TITLE
Could not open browser

### ISSUE THREAD

**Issue by SalsabeelaHasan** [0maru/twitter_login#101]
## Bug report

PlatformException(200, Could not open the browser, probably caused by unavailable custom tabs., null, null)

- android 10 
- this problem happens in all plugin version!

### Which method do you use?

- [x] login()

**Comment by 0maru** [comment]
This plugin uses ChromeCustomTabs.
It can`t be executed if Chrome App is not installed.

Please make sure that Chrome App is installed.

**Comment by SalsabeelaHasan** [comment]
@0maru thanks for your answer, but i have Chrome App in my device.. is there other reasons ?
and i won't to ask u if there is a future plan to add other browsers?

**Comment by SalsabeelaHasan** [comment]
> @SalsabeelaHasan
> 
> > thanks for your answer, but i have Chrome App in my device.. is there other reasons ?
> 
> sorry. I forgot to answer. If you don't have Chrome set as your default browser, your browser may not start.

Understood, thank you!
I'll keep an eye on the updates you make.
and i suggest to add this information to the document to alert us early.

**Comment by SalsabeelaHasan** [comment]
@0maru 
My other question, does this condition also apply to IOS users? what about them, should they have chrome and make it as default browser? What problems with browsers can they face?

**Comment by 0maru** [comment]
@SalsabeelaHasan 
Therefore, iOS does not apply because it uses Safari functionality.

**Comment by 0maru** [comment]
I have released v4.3.0-dev.
This release fixes the Android implementation.
Could you please check if it works?

**Comment by SalsabeelaHasan** [comment]
> 

this is awesome, thank you!
I will do it during the day and tell you the result.

**Comment by SalsabeelaHasan** [comment]
> I have released v4.3.0-dev. This release fixes the Android implementation. Could you please check if it works?

this is awesome, thank you!
I will do it during the day and tell you the result.

**Comment by SalsabeelaHasan** [comment]
> No, that is not required.
> It works even if the default browser is set to Brave.
> Can you tell me what device name and Android OS version you are using so I can investigate in detail?
> 
> My Device Info.
> - Android 12
> - Pixel 5a
> 
> https://user-images.githubusercontent.com/43493921/173360775-d12989e0-abc9-4399-83bd-a760bbaa777c.mp4
> 
> 
> 

Intresting! 
My device info:

- Android 10
- Huawei y9 prime 2019

**Comment by 0maru** [comment]
It worked on a Huawei device.
- HUAWAI P30 lite (MAR-LX2J)
- Android 10
- Chrome is Uninstalled

You should make sure that these two.
1. that the default app is set.
2. that chrome is set as the default browser app and that it works.
