### ISSUE TITLE
Add MacOs support.

### ISSUE THREAD

**Issue by XRayAdamo** [0maru/twitter_login#102]
## Enhancement 

**Describe the Enhancement**
Add MacOs support.

---

## Additional context

Hello. Is it possible to add macOS support? I know that macOs does have ASWebAuthenticationSession so it should not be that hard.

Thank you
---
### Which method do you use?

- [X] login()

- [X] loginV2()

**Comment by 0maru** [comment]
I agree.
I will try to support macOS.

**Comment by XRayAdamo** [comment]
I am actually almost done. Will make PR

**Comment by 0maru** [comment]
I have released 4.3.0-dev.
Thanks 👍
