### ISSUE TITLE
400, Failed to generate request token

### ISSUE THREAD

**Issue by jaibyron** [0maru/twitter_login#103]
## Bug report

I am unable to run the example project successfully. I always get the following exception thrown with both login() and loginV2()

PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>
[✓] Flutter (Channel stable, 2.5.3, on macOS 11.6.3 20G415 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.67.2)
[✓] Connected device (3 available)

</details>

---

### Which method do you use?

- [ ✓ ] login()

- [ ✓ ] loginV2()

**Comment by XRayAdamo** [comment]
Check for network access permissions

**Comment by jaibyron** [comment]
> Check for network access permissions

What should I look at specifically with respect to network permissions ? I get this issue on both iOS and Android in the example project.

**Comment by 0maru** [comment]
Open a browser on the device running the sample project and see if you can view the website.
If you can see the website, the token may be wrong.
Please regenerate it.
