### ISSUE TITLE
This api.twitter.com page can’t be found

### ISSUE THREAD

**Issue by ahndwon** [0maru/twitter_login#107]
## Bug report

**Describe the bug**
After I put in my email and password then click the `Authorize app` button,
I the error below. It used to work right after I upgraded to Elevated access. But suddenly that happens.
Please help! I tried your example but getting same results.

```
This [api.twitter.com](http://api.twitter.com/) page can’t be foundNo webpage was found for the web address: https://api.twitter.com/login?email_disabled=true&redirect_after_login=https%3A%2F%2Fapi.twitter.com%2Foauth%2Fauthorize%3Foauth_token%3DHEBWRwAAAAABeCViAAABgZNqKqc
```
<img src="https://user-images.githubusercontent.com/28426316/175446757-7f4faece-21cf-4097-89b5-1752e23bd5cd.png" width=250 />

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.3.1 21E258 darwin-arm, locale ko-KR)
    • Flutter version 3.0.2 at /opt/homebrew/Caskroom/flutter/2.10.0/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (2주 전), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/ahndwon/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] Connected device (4 available)
    • Pixel 3a (mobile) • 93BAY08XJD                • android-arm64  • Android 12 (API 32)
    • ahndwon (mobile)  • 00008110-000A0CDE147A801E • ios            • iOS 15.5 19F77
    • macOS (desktop)   • macos                     • darwin-arm64   • macOS 12.3.1 21E258 darwin-arm
    • Chrome (web)      • chrome                    • web-javascript • Google Chrome 102.0.5005.115
    ! Error: ahndwon is busy: Preparing the watch for development via ahndwon. Xcode will continue when ahndwon is
      finished. (code -10)

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

</details>

---

### Which method do you use?

- [x] login()

- [x] loginV2()

**Comment by TomasMichal** [comment]
Yes, this error still occurs.

**Comment by TomasMichal** [comment]
This error only occurs if you are not logged in to Twitter...

1. Run Chrome
2. Go to https://twitter.com/
3. Logout
4. Run Flutter app with twitter_login
5. Login to Twitter
6. 404 - page not found

**Comment by thangpnITS** [comment]
i has same problem, how i can fix this

**Comment by 0maru** [comment]
Hi, @thangpnITS could you share [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) with me?

**Comment by thangpnITS** [comment]
@0maru I can't share my code becase security. I only can share for you the image of error. 
when I login form page webview login of SDK like image:
![processed-8e7d030b-37aa-46f8-b61c-b642fc778f66_GBrBqjFv](https://user-images.githubusercontent.com/112608215/192126925-b6b4947a-cc00-4846-9152-fd3c38db4be8.jpeg)
after I enter account then webview will visit to page like this.
![image_2022_09_25T03_24_17_709Z](https://user-images.githubusercontent.com/112608215/192126858-0d89ad6c-836f-4a37-9664-736327b4fa84.png).
but when i tap to icon twitter  and login to twitter web and back to app. Request login again then It will login success.

**Comment by 0maru** [comment]
@thangpnITS 
Ok.

1. Does the redirectURI use app DeepLink, Custom URL Schema?
This plugin will not login successfully with http~~ URL.
because this plugin needs to obtain an Access Token and an Access Secret Token.

2. Do the sample projects work?
Add `example://` to the Twitter Developer Platform callback URL and rewrite the apiKey and apiSecretKey to see if it works.

**Comment by thangpnITS** [comment]
@0maru  I was set redirectURI like appname:// and add it to Twitter Developer Platform callback URL. Some time and some device will had error like img, hasn't any log error show when project run debug.

**Comment by Clashkid155** [comment]
One (some?) of mu user ran into this problem recently. Surprisingly, it doesn't occur for some.
