### ISSUE TITLE
After login twitter account from browser then get stuck to return to my app

### ISSUE THREAD

**Issue by dqcuong2** [0maru/twitter_login#109]
![Screenshot_1657793151](https://user-images.githubusercontent.com/108870525/178958270-524808ff-bae1-4145-91c5-c7314f389d02.png)

**Comment by dqcuong2** [comment]
@0maru Please help

**Comment by han-tm** [comment]
Same problem. I can't solve this problem for 2 weeks now

**Comment by Androidsignal** [comment]
Also i am faceting same issue. Any solution ?

My AndroidManifest Code

**here i'm using multiple  <intent-filter> and this for twitter.**
 ```
 <intent-filter>
     <action android:name="android.intent.action.VIEW" />
           <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                    <data
                         android:host="twoitwoi.com"
                        android:scheme="test" />
 </intent-filter>
```

Login code:

 ```
final twitterLogin = TwitterLogin(
          apiKey: dotenv.env['TWITTER_API_key'].toString(),
          apiSecretKey: dotenv.env['TWITTER_API_SECRET_key'].toString(),
          redirectURI: "test://twoitwoi.com",
        );
```

**Comment by 0maru** [comment]
Please check to see if deeplink is functioning by using the adb command.
If the configuration is correct, the application will start.

```
adb shell am start -W -a android.intent.action.VIEW -d <deeplink url> <your app name>
```

for example
```
adb shell am start -W -a android.intent.action.VIEW -d "test://twoitwoi.com" com.flutter.sample.app
```

**Comment by Androidsignal** [comment]
![image](https://user-images.githubusercontent.com/30517653/179460493-af8ffce3-c4a5-42d0-980e-0d4101abc86c.png)

@0maru But slil not getting any response.

https://user-images.githubusercontent.com/30517653/179461247-d94ce520-2d72-422f-8f9f-c5251649a81f.mov

**Comment by 0maru** [comment]
@Androidsignal 
Are you registering `test://` as a `Callback URI / Redirect URL` in the [Twitter Developer portal](https://developer.twitter.com/en/portal/dashboard)?

**Comment by bulgarian-beast** [comment]
Same problem, and I have verify that I have added the callback url in twitter developer portal @0maru

**Comment by KuldeepVagadiya** [comment]
Hello @0maru any update on this I have same problem, please update us on this, Thanks! 

@bulgarian-beast  are you find any solution this also , please update Thanks!

**Comment by 0maru** [comment]
@KuldeepVagadiya @bulgarian-beast 
Clone the twitter_login repository and verify that the example project works.
If the sample does not work, the [minimum reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) and procedure that will cause this error.

**Comment by KammererTob** [comment]
I had the same issue. Changing the callback to just "twitter://" worked for me. Not sure if it is the specific name or just that it doesn't work with any special characters like "-" or "." in the scheme...
So:

`<data android:scheme="twitter"/>` in the AndroidManifest.xml
and
`redirectURI: 'twitter://',` in the `TwitterLogin` constructor

**Comment by tobi-ayeni** [comment]
Make the host empty or better still remove the host

**Comment by LoadJulz** [comment]
Did anyone solve the issue? iOS everything works fine but for Android I stuck on the callback screen

**Comment by 0maru** [comment]
Close Issue.
If a similar error occurs, reopen the issue.
