### ISSUE TITLE
Stuck on redirected URL after authentication & authorization with Twitter

### ISSUE THREAD

**Issue by akbulutdora** [0maru/twitter_login#110]
## Bug report

**Describe the bug**
After I authenticate and authorize my app to access with Twitter on Android, I go to my callback URL to get the response from my server. The eventStream does not receive any data no matter what I send from my server. I get stuck after being redirected to my callback url with the data printed on the browser.

---

## Additional context

Screenshot of the redirected page, the response body is printed on the top of the screen.
![image](https://user-images.githubusercontent.com/60580158/187220886-147058c9-e629-4691-b9f1-59b718c15364.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19044.1889], locale tr-TR)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Visual Studio - develop for Windows (Visual Studio Derleme Araçları 2019 16.11.2)
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Ultimate Edition (version 2021.3)
[√] VS Code (version 1.70.2)
[√] Connected device (2 available)
[√] HTTP Host Availability

• No issues found!
```

</details>

---

### Which method do you use?

- [x] login()

- [ ] loginV2()

**Comment by 0maru** [comment]
Hey @akbulutdora 
Have you completed setting up your [Android intent](https://github.com/0maru/twitter_login#add-intent-filters-for-incoming-links)?

If you have set up the application, run the following command in terminal to see if the application starts up.
```
adb shell am start -W -a android.intent.action.VIEW -d "INTENT" PACKAGE_NAME
```

for example
```
adb shell am start -W -a android.intent.action.VIEW -d "example://twitter" com.maru.twitter_login
```

**Comment by akbulutdora** [comment]
Maybe what I understand from the redirect URL is wrong. Should the redirect URL redirect to the app or my backend server (I'm not using firebase, already have a twitter oauth that works on my website)?

About the intent setup that you asked, The application does start up, although I get two choices after running the command. Both of them are redirect to the app, but only one works. Also, it only opens the app, I don't know if anything else is expected.

```
Starting: Intent { act=android.intent.action.VIEW dat=https://xxxxx/... pkg=com.xxx.xxx_mobile_app }
Status: ok
LaunchState: COLD
Activity: android/com.android.internal.app.ResolverActivity
TotalTime: 1442
WaitTime: 1528
Complete
```

**Comment by akbulutdora** [comment]
After redirecting to the app, there was no problem. Sorry that I missed the initial notification for your answer.
