### ISSUE TITLE
Support other signins from Twitter

### ISSUE THREAD

**Issue by vin-fandemand** [0maru/twitter_login#111]
## Bug report

**Describe the bug**
If a user signed up with Twitter using Google or Apple sign in, there is no option on the sign in popup to select Sign in with Google or Apple. The user is forced to sign in with id and password. How can we get around this ?
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Which method do you use?

- [ ] login()

- [ ] loginV2()

**Comment by 0maru** [comment]
@vin-fandemand 
Twitter OAuth does not support logging in with Google, Apple, or others.

Please login with your ID and password.
If you have not set a password, please do so in [account settings](https://twitter.com/settings/account).
