### ISSUE TITLE
PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)

### ISSUE THREAD

**Issue by JobGetabu** [0maru/twitter_login#112]
After correct implementation

Worked for a while then started showing

`PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)`

**Comment by 0maru** [comment]
@JobGetabu 
Are you regenerating APIKey in Twitter Developers?

**Comment by Appstute-Arati** [comment]
Any update on above issue?

**Comment by mjolnir91** [comment]
I'm having the exact same issue. I even went into twitter and regenerated the api key and secret and updated TwitterLogin with them. Everything was working about a month ago.

**Comment by 0maru** [comment]
@Appstute-Arati 
no.

Verification is difficult due to lack of information.
If you need to investigate, please provide a sample project.

**Comment by bleszerd** [comment]
I was having the same problem and I noticed that the problem was the callback url. 

On Android:
Make sure the callback you set in your Twitter app's settings is exactly as it is in the Android Manifest

```xml
<!-- ... -->

 <intent-filter>
    <action android:name="android.intent.action.VIEW" />

    <category android:name="android.intent.category.DEFAULT" />
    <category android:name="android.intent.category.BROWSABLE" />

    <!-- match "application://callback" URL -->
    <data
        android:host="callback"
        android:scheme="application" />

<!-- ... -->
```

Unfortunately I can't help with iOS
