### ISSUE TITLE
How to open Twitter login app instead of the website?

### ISSUE THREAD

**Issue by lecanhhiep** [0maru/twitter_login#116]
Hi,

I see this plugin require user login with username and password.
Is this possible to open twitter app if they have installed it, and all they need to do is clicking Authorize button  instead of typing the username/password, for me it looks more secure  and more UX.

Thank you!

**Comment by 0maru** [comment]
That login method cannot be supported by this plugin.

[TwitterKit](https://github.com/twitter-archive/twitter-kit-ios) is required to implement that login method.
However, the development of TwitterKit is finished.

Sorry.
