### ISSUE TITLE
Unable to login for iOS or Android

### ISSUE THREAD

**Issue by real1900** [0maru/twitter_login#118]
## Bug report

**Describe the bug**

getting the following error for iOS 

Unhandled Exception: [firebase_auth/invalid-credential] Failed to fetch resource from https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true, http status: 401, http response: {"errors":[{"code":32,"message":"Could not authenticate you."}]}
---
so noting happens after this for iOS 

for Android it is stuck at redirection screen . 

Tried both v1 and v2 and followed all steps in documentation .

**Comment by 0maru** [comment]
Catch error and return null if user data could not be retrieved in v4.3.2.
If the TwitterAPI is restricted or the rate limit is reached, an error will be caught and null will be returned.

**Comment by 0maru** [comment]
Close Issue.
If a similar error occurs, reopen the issue.
