### ISSUE TITLE
vivo, Android，Could not open browser

### ISSUE THREAD

**Issue by wanghuasheng** [0maru/twitter_login#121]
in Android phone ,vivoS12，iaomi mix2，Could not open browser。

 if (pm.resolveService(serviceIntent, 0) != null) {
         packagesSupportingCustomTabs.add(info.activityInfo.packageName);
}

cant resolveService

can not open custom tabs

PlatformException(INVALID_AUTHORIZATION, can not open custom tabs., null, null)

I hope to skip to other default browsers or webview ，when there is no Chrome browser available

you can use androidx.webkit:webkit:1.3.0 replace androidx.browser:browser:1.3.0

**Comment by 0maru** [comment]
Since ChromeCustomTabs appears to be implemented in various browsers,
I would like to proceed in the direction of expanding the target browsers.

**Comment by wanghuasheng** [comment]
> 由于 ChromeCustomTabs 似乎在各种浏览器中实现， 我想继续扩展目标浏览器的方向。



> Since ChromeCustomTabs appears to be implemented in various browsers, I would like to proceed in the direction of expanding the target browsers.

proceed in the direction of expanding the target browsers is good！

You can also jump to webkit.webview when you cant resolveService, without any conflict。

**Comment by wanghuasheng** [comment]
I solved this problem using fireBase, and one line of code is very simple！

**Comment by YaakovHuang** [comment]
> I solved this problem using fireBase, and one line of code is very simple！

I also encountered the same problem. How did you solve this problem?
