### ISSUE TITLE
Type 'VoidCallback' not found

### ISSUE THREAD

**Issue by Oleksandr32** [0maru/twitter_login#123]
## Bug report

**Describe the bug**
Hi, there is a bug in the last release of the plugin. Looks like there is no import for 'VoidCallback' in `auth_browser.dart` file.
Could you please check and make a hotfix?

```
twitter_login-4.4.0/lib/src/auth_browser.dart:20:3: Error: Type 'VoidCallback' not found. VoidCallback onClose;
```

<img width="1326" alt="Screenshot 2023-05-22 at 14 49 32" src="https://github.com/0maru/twitter_login/assets/24620659/cdcae7a9-224e-4cb1-ae9f-b51739fcdd5b">

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 3.0.0, on macOS 13.0.1 22A400 darwin-arm, locale en-UA)
    • Flutter version 3.0.0 
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ee4e09cce0 (1 year ago), 2022-05-09 16:45:18 -0700
    • Engine revision d1b9a6938a
    • Dart version 2.17.0
    • DevTools version 2.12.2
```

</details>

---

**Comment by 0maru** [comment]
I could not confirm this error.
Are you experiencing the same error now?

**Comment by jmarrr** [comment]
I am currently experiencing this error
![Untitled](https://github.com/0maru/twitter_login/assets/26637741/7659f893-a8ee-481b-9c16-d5471612d7b7)

**Comment by Oleksandr32** [comment]
hi @0maru, I have fixed it by adding 
```
import 'package:flutter/material.dart';
```
to `auth_browser.dart` file, because there's no import for `VoidCallback` type.
