### ISSUE TITLE
do i  need a server to handle token?

### ISSUE THREAD

**Issue by bakboem** [0maru/twitter_login#15]

**Comment by 0maru** [comment]
If your service is using a server, it is necessary to keep the login session.
If you are using such as Auth0 or Firebase, you don't need a server.

**Comment by bakboem** [comment]
Unable to verify Google callbackURL


 <key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>https://food-xxx.firebaseapp.com/__/auth/handler</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>>app</string>
			</array>
		</dict>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.googleusercontent.apps.67867803-ip4j99026sf7604japag7lrg02tgfi0v</string>
			</array>
		</dict>
	</array>

**Comment by 0maru** [comment]
The Firebase callback URL to use are as follows.
You can't put https in info.plist.
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLName</key>
    <!-- Registered Callback URLs in TwitterApp -->
    <string>my-app-12345.firebaseapp.com/__/auth/handler</string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>app</string>
    </array>
  </dict>
</array>
```

**Comment by bestkid1234** [comment]
> my-app-12345.firebaseapp.com/__/auth/handl

Hi! How shoud I put in `AndroidManifest.xml` the callback URL for firebase?

**Comment by 0maru** [comment]
@bestkid1234 
I don't think you can use the Firebase callback URL on Android.
So, please add your callback URL on Twitter Developers.

**Comment by bestkid1234** [comment]
@0maru So I don't need to do any changes at `AndroidManifest.xml`?

**Comment by bakboem** [comment]
> The Firebase callback URL to use are as follows.
> You can't put https in info.plist.
> 
> ```
> <key>CFBundleURLTypes</key>
> <array>
>   <dict>
>     <key>CFBundleTypeRole</key>
>     <string>Editor</string>
>     <key>CFBundleURLName</key>
>     
>     <string>my-app-12345.firebaseapp.com/__/auth/handler</string>
>     <key>CFBundleURLSchemes</key>
>     <array>
>       <string>app</string>
>     </array>
>   </dict>
> </array>
> ```



> @bestkid1234
> I don't think you can use the Firebase callback URL on Android.
> So, please add another callback URL on Twitter Developers.



> The Firebase callback URL to use are as follows.
> You can't put https in info.plist.
> 
> ```
> <key>CFBundleURLTypes</key>
> <array>
>   <dict>
>     <key>CFBundleTypeRole</key>
>     <string>Editor</string>
>     <key>CFBundleURLName</key>
>     
>     <string>my-app-12345.firebaseapp.com/__/auth/handler</string>
>     <key>CFBundleURLSchemes</key>
>     <array>
>       <string>app</string>
>     </array>
>   </dict>
> </array>
> ```

thank you !~ it  worked!

**Comment by 0maru** [comment]
@bakboem 
No.
You need to write the callback URL you registered with [Twitter Developer](https://developer.twitter.com/en/portal/dashboard) in AndroidManifest.xml

![スクリーンショット 2020-12-05 22 09 02](https://user-images.githubusercontent.com/43493921/101243906-957a7100-3746-11eb-9495-f57e1ddbd83d.png)

For example add `example://`

```
<intent-filter>
  <action android:name="android.intent.action.VIEW" />
  <category android:name="android.intent.category.DEFAULT" />
  <category android:name="android.intent.category.BROWSABLE" />
  <!-- Accepts URIs that begin with "example://” -->
  <!-- Registered Callback URLs in TwitterApp -->
  <data android:scheme="example"
    android:host="" /> <!-- host is option -->
</intent-filter>
```

**Comment by bestkid1234** [comment]
> @bakboem
> No.
> You need to write the callback URL you registered with [Twitter Developer](https://developer.twitter.com/en/portal/dashboard) in AndroidManifest.xml
> 
> ![スクリーンショット 2020-12-05 22 09 02](https://user-images.githubusercontent.com/43493921/101243906-957a7100-3746-11eb-9495-f57e1ddbd83d.png)
> 
> For example add `example://`
> 
> ```
> <intent-filter>
>   <action android:name="android.intent.action.VIEW" />
>   <category android:name="android.intent.category.DEFAULT" />
>   <category android:name="android.intent.category.BROWSABLE" />
>   
>   
>   <data android:scheme="example"
>     android:host="" /> 
> </intent-filter>
> ```

Sooo.... I can replace `example://` with whatever I want?

**Comment by 0maru** [comment]
@bestkid1234 
Yes.
You can alter it any way you like.
