### ISSUE TITLE
twitter_login bug

### ISSUE THREAD

**Issue by roberthook823** [0maru/twitter_login#17]
I've been using flutter_twitter_login so far. But now the support has been suspended, so I used Twitter_login for the first time. Strangely, however, after logging in, it is redirected to the app and running a new process instead of printing the results. So when you log in to Twitter several times, several main threads are created. What's the matter? I'm running on Android now. So I tested Twitter_login's sample code, but it was the same. why? Help me, please.
![Untitled](https://user-images.githubusercontent.com/59207864/102522321-73370a80-40d9-11eb-8d39-a204e5652160.png)
![Untitled](https://user-images.githubusercontent.com/59207864/102522412-8ba72500-40d9-11eb-806c-42eaaacb7f93.png)
![Untitled](https://user-images.githubusercontent.com/59207864/102522548-bb562d00-40d9-11eb-8b3f-ee9cfd8521c0.png)

**Comment by 0maru** [comment]
Have you added `example://` to the CallBackURLs in [Twitter Developer](https://developer.twitter.com/en)?

**Comment by roberthook823** [comment]
Yes I do
![Untitled](https://user-images.githubusercontent.com/59207864/102793667-928daa80-43ed-11eb-84fc-9decfa895415.png)

**Comment by 0maru** [comment]
It did not reappear.
Can you post the console log when you run the login process?

**Comment by roberthook823** [comment]
![Uploading Untitled.png…]()

**Comment by roberthook823** [comment]
![Untitled](https://user-images.githubusercontent.com/59207864/103160115-84d48c80-4814-11eb-8cbe-ba3c5c11ec1f.png)

**Comment by roberthook823** [comment]
Restarted application in 885ms.
I/flutter (15873): https://api.twitter.com/oauth/authorize?oauth_token=SdNbKAAAAAABKMHAAAABdqEjcqQ
D/EGL_emulation(15873): eglMakeCurrent: 0xa7535040: ver 3 0 (tinfo 0x951ec5b0)
F/crash_dump32(16347): crash_dump.cpp:246] target died before we could attach (received main tid = 16345)
D/EGL_emulation(15873): eglCreateContext: 0x94c83c00: maj 3 min 0 rcv 3
D/EGL_emulation(15873): eglCreateContext: 0x94c83c60: maj 3 min 0 rcv 3
D/        (15873): HostConnection::get() New Host Connection established 0x8ecfd6c0, tid 16367
D/EGL_emulation(15873): eglMakeCurrent: 0x94c83c60: ver 3 0 (tinfo 0x96274550)
I/zygote  (15873): Do partial code cache collection, code=26KB, data=30KB
I/zygote  (15873): After code cache collection, code=26KB, data=30KB
I/zygote  (15873): Increasing code cache capacity to 128KB
D/        (15873): HostConnection::get() New Host Connection established 0x925b2cc0, tid 16366
D/EGL_emulation(15873): eglMakeCurrent: 0x94c83c00: ver 3 0 (tinfo 0xa9003d50)
D/EGL_emulation(15873): eglMakeCurrent: 0xa7535040: ver 3 0 (tinfo 0x951ec5b0)
D/EGL_emulation(15873): eglMakeCurrent: 0x94c83c00: ver 3 0 (tinfo 0xa9003d50)
D/skia    (15873): Shader compilation error

**Comment by 0maru** [comment]
Try `flutter doctor` and `flutter clean` once, and then try logging in again.
If you still cannot log in, please tell us what type of desktop hardware the emulator is running on.

 Also, do you get the same error on the actual android device?
