### ISSUE TITLE
how to signout ?

### ISSUE THREAD

**Issue by niypoo** [0maru/twitter_login#21]
How can I do signout ?

**Comment by 0maru** [comment]
This plugin can not not signout.
because it uses Twitter session to login.
However, you can change the login information of the application by forcing the login.

For example
```:dart
final twitterLogin = TwitterLogin(
  apiKey: xxx,
  apiSecretKey: xxx,
  redirectURI: xxx,
);

// use forceLogin param
final authResult = twitterLogin.login(forceLogin: true);
```
