### ISSUE TITLE
【iOS】Unable to process request

### ISSUE THREAD

**Issue by mitUltimate** [0maru/twitter_login#22]
I encountered a problem that when running on iOS, after logging in to Twitter, the message of the attached image was displayed and the transition to the app did not occur.

Since I received a login notification from Twitter, so I think the login itself works.
Do you have any idea to solve this problem?

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-31 at 21 43 41](https://user-images.githubusercontent.com/46930634/106384433-251e6200-640e-11eb-850a-a695da681c05.png)

**Comment by gyakhoe** [comment]
> I encountered a problem that when running on iOS, after logging in to Twitter, the message of the attached image was displayed and the transition to the app did not occur.
> 
> Since I received a login notification from Twitter, so I think the login itself works.
> Do you have any idea to solve this problem?
> 
> ![Simulator Screen Shot - iPhone 12 Pro Max - 2021-01-31 at 21 43 41](https://user-images.githubusercontent.com/46930634/106384433-251e6200-640e-11eb-850a-a695da681c05.png)

I got the same issue

**Comment by mitUltimate** [comment]
I resolved this problem by the following procedure. Note that your-app:// indicates the root for the deep link.
Set TwitterDeveloper configuration to firebase callback URL and your-app://.
Set the URL schema for info.plist to the reverse client id  and your-app://,
Set intent-filter in AndroidManifest.xml to your-app://.
Set redirectURL in the TwitterLogin constructor to your-app://.

He shared this method with us. Thankful to him!
https://twitter.com/appcreator_masa/status/1343872642739105796?s=20

**Comment by mitUltimate** [comment]
I resolved this problem by the following procedure. Note that your-app:// indicates the root for the deep link.

・TwitterDeveloper configuration to firebase callback URL and your-app://.
・the URL schema for info.plist to the reverse client id  and your-app://,
・intent-filter in AndroidManifest.xml to your-app://.
・redirectURL in the TwitterLogin constructor to your-app://.

He shared this method with us. I'm thankful to him!
https://twitter.com/appcreator_masa/status/1343872642739105796?s=20

**Comment by mitUltimate** [comment]
I resolved this problem by the following procedure. Note that your-app:// indicates the root for the deep link.
 
・Setting TwitterDeveloper configuration to firebase callback URL and your-app://.
・Setting the URL schema for info.plist to the reverse client id  and your-app://,
・Setting intent-filter in AndroidManifest.xml to your-app://.
・Setting redirectURL in the TwitterLogin constructor to your-app://.

He shared this method with us. I'm thankful to him!
https://twitter.com/appcreator_masa/status/1343872642739105796?s=20
