### ISSUE TITLE
App redirect!

### ISSUE THREAD

**Issue by RAIERIN** [0maru/twitter_login#25]
After successfully logging in it does not redirect to app!

![Screenshot_1614422888](https://user-images.githubusercontent.com/56987934/109385113-88ba8300-7919-11eb-94e5-66066c4e58c0.png)

**Comment by Adrek** [comment]
I hade the same problem.

I try it on my physical device (Xiaomi Redmi 5 Plus Android 8) and only shows this screenshot:
1- https://i.imgur.com/vocOoTd.png

Then, I try it on a Emulator device and show this screenshots:
1- https://i.imgur.com/phw9QX4.png
2- 300 milliseconds aprox. after shows this: https://i.imgur.com/yrhKgAf.png

**Comment by RAIERIN** [comment]
Today I am getting this: What is the problem
![Screenshot_1614485048](https://user-images.githubusercontent.com/56987934/109407601-3ffeda80-79aa-11eb-9ecb-78c47b2b27f0.png)

**Comment by junaidlodhi22** [comment]
The same error "page does not exist". Did you solve it?

**Comment by 0maru** [comment]
Could you please share the code for Android settings and call login method?
I think the callback URL is not registering with Twitter Developer Portal.

**Comment by JT501** [comment]
same issue here, using version v3.0.1-nullsafety.0 .

Android
```xml
<intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <category android:name="android.intent.category.BROWSABLE"/>
                <data android:scheme="@string/fb_login_protocol_scheme"/>
                <data android:scheme="mah-jong-la://"/>
</intent-filter>
```

iOS
```xml
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleTypeRole</key>
        <string>Editor</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>fbxxxxxxxxxx</string>
            <string>com.googleusercontent.apps.xxxxxxx</string>
            <string>mah-jong-la</string>
        </array>
    </dict>
</array>
```


I have added `mah-jong-la://` in Twitter dev portal.

**Comment by JT501** [comment]
feel free to have a look on #31 , see if it helps

**Comment by yayamochi** [comment]
I have the same problem.
iOS App is well, but Android App doies not redirect to app.

I added intent filters in AndroidManifest.xml
```
            <intent-filter>
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="example"/>
            </intent-filter>
```

**Comment by 0maru** [comment]
@yayamochi 
You will need to add `android.intent.action.VIEW` before the `android.intent.category.DEFAULT`.

```
<intent-filter>
  +  <action android:name="android.intent.action.VIEW" /> // <- added
     <category android:name="android.intent.category.DEFAULT" />
     <category android:name="android.intent.category.BROWSABLE" />
     <data android:scheme="example"/>
</intent-filter>
```

**Comment by 0maru** [comment]
Without`android.intent.action.VIEW`, will not redirect to Android App.

Can I view the code in AndroidManifest.xml if `android.intent.action.VIEW` exists but is not redirected?

**Comment by yayamochi** [comment]
@0maru 
Sorry, I forgot `android.intent.action.VIEW.`
It went well. 
Thanks you for answering.
