### ISSUE TITLE
[CLOSE] I fixed it was my mistake :)

### ISSUE THREAD

**Issue by furkankurt** [0maru/twitter_login#3]
Hello, I tried your package but I couldn't open the login activity. I think it's opening on a webview. But my app always return "Failed Authorization Required" error. What do you think? And also I don't understan the redirectURI field. Thank you :)

**Comment by furkankurt** [comment]
You are from Japan I think and I heard there was a flood and landslide disaster, I'm really sorry. Get well soon. 
Loves from Turkey 🇹🇷

**Comment by 0maru** [comment]
I'm glad it's been resolved.
Thanks.

**Comment by niypoo** [comment]
> Hello, I tried your package but I couldn't open the login activity. I think it's opening on a webview. But my app always return "Failed Authorization Required" error. What do you think? And also I don't understan the redirectURI field. Thank you :)

hello @furkankurt  what was your bad , I'm facing same issue and I using firebase auth

**Comment by niypoo** [comment]
Ok, I know what is missing , I forget add schema url into my twitter app, thanks all
