### ISSUE TITLE
depends on twitter_login 3.0.1 which depends on crypto ^3.0.0, crypto ^3.0.0 is required.

### ISSUE THREAD

**Issue by nhatmoc97** [0maru/twitter_login#30]
this version conflict with some package in my project.

**Comment by nhatmoc97** [comment]
> Using version 2.1.4 should solve this problem.

but firebase_core, firebase_auth,... conflict same

**Comment by 0maru** [comment]
oh...

You can try dependency overrides for crypto.
https://dart.dev/tools/pub/dependencies#dependency-overrides
