### ISSUE TITLE
Strange Login Issue

### ISSUE THREAD

**Issue by JT501** [0maru/twitter_login#31]
Here is my code:

```dart
final TwitterLogin twitterLogin = TwitterLogin(
    apiKey: 'key',
    apiSecretKey: 'secret',
    redirectURI: 'url',
  );
final AuthResult authResult = await twitterLogin.login();

print(authResult.status);
if (authResult.status == TwitterLoginStatus.error ||
    authResult.status == TwitterLoginStatus.cancelledByUser) {
  print(authResult.errorMessage);
  return null;
}
```
If I enter **Email** to login twitter, it will direct to this Page Not Found.
![simulator_screenshot_A02CC8A5-666E-4391-82F3-B7A6B3007FEE](https://user-images.githubusercontent.com/19503156/110967888-d57a7100-8391-11eb-8f2b-1758021936e3.png)

**HOWEVER**, if I enter **Username** to login, it will successfully direct me to correct Authorise page. I think it is a bug from Twitter side.

But after I clicked authorise my app, it failed to get the token. I logged the error message :
```
I/flutter ( 9869): null
I/flutter ( 9869): type 'Null' is not a subtype of type 'String'
```

**Comment by JT501** [comment]
More error details

```
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
#0      new User._ (package:twitter_login/entity/user.dart:30:21)
#1      User.getUserData (package:twitter_login/entity/user.dart:54:19)
<asynchronous suspension>
#2      TwitterLogin.login (package:twitter_login/src/twitter_login.dart:104:24)
<asynchronous suspension>
```

**Comment by JT501** [comment]
### Solution:

After some deep digs, I found out it is caused by user's `email` being **null** and I figured out the response does not return `email`. So spending almost half day, I finally found out I have to **turn on** `Request email address from users` and added Terms and Privacy links.
![Screenshot 2021-03-13 at 1 22 25 AM](https://user-images.githubusercontent.com/19503156/110975352-9a307000-839a-11eb-9694-e99cfe0737d2.png)

After that, all the above mentioned strange behaviours are gone. :rocket::rocket::rocket::rocket:

**Comment by 0maru** [comment]
Thank you.
I'll add this to the README.
