### ISSUE TITLE
v3.0.4 Android build failing

### ISSUE THREAD

**Issue by sentd94** [0maru/twitter_login#37]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\User\AndroidStudioProjects\flutter_app\build\flutter_inappwebview\intermediates\library_manifest\debug\AndroidManifest.xml:7:5-11:15: AAPT: error: unexpected element <queries> found in <manifest>.

The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.

**Comment by 0maru** [comment]
@sentd94 
What is the version of gradle in android/build.gradle?
I think using 3.5.4 will solve the problem.

```
classpath 'com.android.tools.build:gradle:3.5.4'
```

If not, please share additional information.
`android/build.gradle` or `flutter run -v`

**Comment by sentd94** [comment]
The version of gradle was `3.5.0`
Changing it to `3.5.4` seems to have fixed the issue.
