### ISSUE TITLE
No option to retrieve User Id

### ISSUE THREAD

**Issue by bojidartonchev** [0maru/twitter_login#38]
Hello,

I noticed there is no option to retrieve currently logged in user's id.
It should be 19-digits string.

Am I missing something, or this is not yet implemented?

Thanks!

**Comment by 0maru** [comment]
@bojidartonchev 
It is not implemented.

If necessary, I will implement it, but I can't find any documentation for user's id,
so I can't start implementing it.
Can you give me the documentation?

**Comment by bojidartonchev** [comment]
Hello @0maru,

This is what I am looking at atm.
[Twitter User Object](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/user)

**Comment by bojidartonchev** [comment]
Thank you very much for the quick response.
