### ISSUE TITLE
No Way To Logout?

### ISSUE THREAD

**Issue by Andrious** [0maru/twitter_login#42]
Great work!  Null safety and everything!
However, and I may be missing something here, no logout routine?

```
  /// Logs the currently logged-in user out.
  Future<void> logOut() async => channel.invokeMethod('logOut', _keys);
```

**Comment by 0maru** [comment]
This plugin is using the browser session, so you can't logout.
Instead, it can use force login.

```
login(forceLogin: true);
```

If you don't use sessions, switching between accounts is easier, but i don't think it's smart.
