### ISSUE TITLE
Cancel issue in Android

### ISSUE THREAD

**Issue by JT501** [0maru/twitter_login#44]
when I clicked the 'X' in webview, the Future does not end unless I added timeout on it.

```
final AuthResult authResult = await twitterLogin.login();
```

PS. It works fine if I click the 'Cancel' button in the twitter login page.

My guess:

https://github.com/0maru/twitter_login/blob/master/lib/src/twitter_login.dart#L71
``` 
final browser = ChromeCustomTab(
          onClose: () {
            if (!completer.isCompleted) {
              completer.complete(null);
            }
          },
        );
```
It looks like the closure onClose() causes the issue. It cannot transfer `completer.complete(null);` successfully.

**Comment by 0maru** [comment]
@JT501 
There was a bug that Future did not complete.
This has been fixed in 3.0.8.
