### ISSUE TITLE
issue related with other depended package

### ISSUE THREAD

**Issue by niypoo** [0maru/twitter_login#48]
I have noticed a lot of crashes happened with my users with a package I have never used so searching and found your package I only used depended on this package that called "pichillilorenzo/flutter_inappwebview"

the crash error is 
```
ChromeCustomTabsActivity.java line 42
com.pichillilorenzo.flutter_inappwebview.chrome_custom_tabs.ChromeCustomTabsActivity.onCreate
```
<img width="1038" alt="Screen Shot 2021-05-16 at 7 53 08 PM" src="https://user-images.githubusercontent.com/13227239/118407269-57cc2d80-b680-11eb-8c2a-49a36c53d134.png">

this is a issue topic about this issue
https://github.com/pichillilorenzo/flutter_inappwebview/issues/665

so please investigation more about that issue

**Comment by niypoo** [comment]
I have found this issue in android related with this package and I'm investigation more about this issue now, for any one wants help.

```
 Exception: HttpException: Failed Forbidden
E/flutter (24743): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: Exception: HttpException: Failed Forbidden
```

**Comment by niypoo** [comment]
Any update !!

**Comment by 0maru** [comment]
@niypoo 
I'm writing code to remove flutter_inappwebview as a dependency.
Please wait a moment.

**Comment by eunsolkang** [comment]
Same Issue

![스크린샷 2021-05-27 오전 2 51 41](https://user-images.githubusercontent.com/22852287/119707764-79a28d00-be96-11eb-91b1-f9e44c37d5b4.png)

**Comment by 0maru** [comment]
@niypoo 
I have finished the implementation.
It will be merged into the master soon and the latest version will be released.

**Comment by 0maru** [comment]
@niypoo
v4.0.0 has been released.
Please use flutter 2.0.0 or later version as null-safety is enabled.

**Comment by niypoo** [comment]
> @niypoo
> 
> v4.0.0 has been released.
> 
> Please use flutter 2.0.0 or later version as null-safety is enabled.
> 
> 

Thanks 🙏
