### ISSUE TITLE
Why do I open a web page instead of redirecting to the Twitter App when logging in with Twitter

### ISSUE THREAD

**Issue by hw20101101** [0maru/twitter_login#50]
### I want to authorize via Twitter App

The version i use `twitter_login: ^3.0.8`

This is the webpage that my app opens when requesting authorization from Twitter：

![20210603171343](https://user-images.githubusercontent.com/9107226/120620567-ac004b80-c48f-11eb-9e10-179c16e13a2d.jpg)

**Comment by 0maru** [comment]
As the Twitter Kit SDK is not supported by Twitter, inc. 
this plugin does not support login via the Twitter App. 
You can use [flutter_twitter_login](https://pub.dev/packages/flutter_twitter_login) to log in using the Twitter App.
