### ISSUE TITLE
catch an error when canceled on iOS

### ISSUE THREAD

**Issue by KyoheiG3** [0maru/twitter_login#51]
After taps the cancel button on the login dialog, the result returns with `TwitterLoginStatus.error` not `TwitterLoginStatus.cancelledByUser`.

The error message is `Null check operator used on a null value`.

twitter_login: ^3.0.8
iOS version 14.4.2

**Comment by 0maru** [comment]
@KyoheiG3 
i'm making major changes.
I start to this issue when i'm done.

**Comment by 0maru** [comment]
Fixed a bug in v4.0.0 that caused an error when pressing cancel in the login dialog.
