### ISSUE TITLE
Haven't any log out method?

### ISSUE THREAD

**Issue by LucPham** [0maru/twitter_login#55]

**Comment by 0maru** [comment]
This plugin uses browser cookies, so if you want to log out of your Twitter account you will need to log out in your browser.
If you want to log out of your service, you should be able to do so by disable the authentication token for your service.
You should also set `force_login: true` if you want to select an Twitter account when log in with your service.

**Comment by panchalAlpit** [comment]
@0maru Please implement the logout functionality like [this](https://pub.dev/packages/flutter_twitter/example) plugin.
So we can use very friendly.

**Comment by 0maru** [comment]
@panchalAlpit 
This is difficult to implement as the TwitterAPI dosn`t provide a logout API of a Twitter account.
Is the force_login option not enough functionality for you?
