### ISSUE TITLE
Can anyone help me pls?

### ISSUE THREAD

**Issue by thealmamun** [0maru/twitter_login#57]
I am trying to redirect to my app after login complete. But unable to do that , it's showing 404 page after login & can't get the my twitter profile info like name, email etc. it showing this page and not navigating my app WelcomeScreen https://imgur.com/XdW82TU

Callback url set to twitter dev account: https://imgur.com/xOsEqOs

Android manifest:

     <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                
                <data android:scheme="twittersdk://"
                    android:host="gizmos" /> 
            </intent-filter>

Source Code:
 static Future<UserCredential> signInWithTwitter(
      {BuildContext? context}) async {
    String? newMessage;

    // Trigger the sign-in flow

    final authResult = await twitterLogin.login();

    // Create a credential from the access token
    final twitterAuthCredential = TwitterAuthProvider.credential(
      accessToken: authResult.authToken.toString(),
      secret: authResult.authTokenSecret.toString(),
    );

    print(twitterAuthCredential!.providerId);

    // Once signed in, return the UserCredential
    UserCredential userCredential =
        await FirebaseAuth.instance.signInWithCredential(twitterAuthCredential);

    log('your message here');
    log('userCredential.user');
    log(userCredential.user.toString());
    User? user = userCredential.user;
    DocumentSnapshot? doc = await Globals.userRef.doc(user!.uid).get();
    if (!doc.exists) {
      Globals.userRef.doc(user!.uid).set({
        'uid': user!.uid,
        'email': user.email,
        'firstName': "firstName",
        'lastName': "lastName",
        'displayName': user!.displayName,
        'password': 'hashedPassword',
        'userName': user.email,
        'bio': Globals.loremText,
        'photoUrl': user!.photoURL,
        'phoneNumber': "phoneNumber",
        'userType': "Facebook",
        'publicUrl': "url",
        "isAdmin": false,
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
        'lastLoggedIn': FieldValue.serverTimestamp(),
      });

      switch (authResult.status) {
        case TwitterLoginStatus.loggedIn:
          newMessage = 'User ${user.email} LoggedIn Successfully!';
          ScaffoldMessenger.of(context!).showSnackBar(
            Globals.customSnackBar(
              content: newMessage,
            ),
          );
          break;
        case TwitterLoginStatus.cancelledByUser:
          newMessage = 'Login cancelled by user.';
          ScaffoldMessenger.of(context!).showSnackBar(
            Globals.customSnackBar(
              content: newMessage,
            ),
          );
          break;
        case TwitterLoginStatus.error:
          newMessage = 'Login error: ${authResult.errorMessage}';
          ScaffoldMessenger.of(context!).showSnackBar(
            Globals.customSnackBar(
              content: newMessage,
            ),
          );
          break;
      }
    }
    Navigator.push(
        context!,
        MaterialPageRoute(
            builder: (context) => WelcomeScreen(
                  user: user,
                )));
    return userCredential;
  }

**Comment by 0maru** [comment]
@thealmamun
This plugin is not compatible with the TwitterSDK.
Please configure [DeepLink](https://developer.android.com/training/app-links/deep-linking).
