### ISSUE TITLE
cannot configure the iOS project

### ISSUE THREAD

**Issue by mohadel92** [0maru/twitter_login#59]
Hi,
i tried multiple times to configure the iOS project
via using URL Scheme and the app still crashes
ios version : 14.5 / 12.3
flutter : 1.22.6
twitter package : 2.1.4
`'NSInvalidArgumentException', reason: 'The provided scheme is not valid. A scheme should not include special characters such as ":" or "/".'`

**Comment by 0maru** [comment]
@mohadel92 
Since iOS 14.5, using :// in a scheme causes a crash.
Please update this plugin because this problem is an iOS specification.
If you don't support flutter 2.0 and can't update, please fork it and use it.


open twitter_login.dart and make the following changes.
```
resultURI = await _channel.invokeMethod('authentication', {
  'url': requestToken.authorizeURI,
-  'redirectURL': redirectURI,
+  'redirectURL': Uri.parse(redirectURI).scheme, 
});
```

**Comment by mohadel92** [comment]
@mono0926  more explanation for this process?
