### ISSUE TITLE
iOS Configuration issue

### ISSUE THREAD

**Issue by phuhungtran** [0maru/twitter_login#60]
Hello
I set it up on Android but It doesn't redirect to my app on iOS
I put this into my info.plist
```
<key>CFBundleURLTypes</key>
<array>
  <dict>
    <key>CFBundleTypeRole</key>
    <string>Editor</string>
    <key>CFBundleURLName</key>
    <string></string>
    <key>CFBundleURLSchemes</key>
    <array>
      <string>https://xxx.page.link/xxx</string>
    </array>
  </dict>
</array>
```

Please help me.

**Comment by phuhungstdio** [comment]
@0maru please check my issue and support me.
One more thing, Apple doesn't accept CFBundleURLName <string></string> when I submit to TestFlight

**Comment by 0maru** [comment]
@phuhungtran 
Use DeepLink.
Dynamic Links does not have the ability to pipe query parameters.

Please refer to Example for how to write DeepLink.

Specify a scheme, not an FQDN, in CFBundleURLSchemes.
Since you specify an FQDN, I think it is rejected by Apple.

**Comment by phuhungtran** [comment]
@0maru 
I used this dynamic link on Android and it worked.
And I don't see the example which has the deep link.
I added CFBundleURLSchemes like your example info.plist.
