### ISSUE TITLE
Twitterlogout 

### ISSUE THREAD

**Issue by VipulDamor** [0maru/twitter_login#62]
i am not able to find twitter logout function it will be great if you can add it

**Comment by 0maru** [comment]
@VipulDamor 
Twitter OAuth API doesn't expose the logout API, so it is impossible to implement.

Instead, you can use the force_login option to forces the user to enter their credentials to ensure the correct users account is authorized.
Can't the force_login option satisfy the requirement?

**Comment by VipulDamor** [comment]
okay thanks
