### ISSUE TITLE
Redirect on Android failing

### ISSUE THREAD

**Issue by mohamedali170** [0maru/twitter_login#63]
I have a problem with targetsdkversion 30, the webview doesn't return to the app it gives ERR_UNKNOWN_URL_SCHEME
You can see the screen from here: https://drive.google.com/file/d/1LX1YQEn7QOmCN_P-KtA4UNvX-PJHIaJu/view?usp=sharing

minSdkVersion 21
compileSdkVersion 30
targetsdkversion: 30
Flutter: 1.22.6 
twitter_login: 2.1.4

**Comment by mohamedali170** [comment]
@0maru I need ur help plz

**Comment by mohamedali170** [comment]
@0maru I need your support, please

**Comment by 0maru** [comment]
@mohamedali170 
Please share the source code.
If the source code does not exist, i will not be able to support it.
Also, if the source code is private, please share the minimum configuration.

**Comment by mohamedali170** [comment]
This is my build.gradle file

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.maru.twitter_login_example"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
}
`
and this is AndroidManifest.xml
`<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.maru.twitter_login_example">
    
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="twitter_login_example"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            
            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                
                <data android:scheme="example"/> 
            </intent-filter>
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />
    </application>
</manifest>
`

**Comment by mohamedali170** [comment]
@0maru 
You can use this [example](https://github.com/0maru/twitter_login/tree/2d15dcc6afab43d2945eea7b47c18c7c66832203/example) then change the following:

- targetSdkVersion to 30
- compileSdkVersion to 30
- minSdkVersion to 21

**Comment by mohamedali170** [comment]
@0maru  any updates?

**Comment by 0maru** [comment]
@mohamedali170 
I can’t update because this plugin does not support non-null-safety code.
It works fine with the latest version.
Please consider upgrading Flutter version and plugin version.

**Comment by mohamedali170** [comment]
@0maru 
At the current time, the update will be very difficult. If you could help with the current situation, I'd be thankful
