### ISSUE TITLE
Unable to open custom tabs for twitter auth

### ISSUE THREAD

**Issue by ShotaImamura** [0maru/twitter_login#64]
In some environments, the custom tab couldn't open.

It works on the android Pixel 4 API30 emulator,
 however, It didn't on the android Pixel 3a API30 emulator, Pixel 5 actual device( android 12 ), and another Android device (android11).

Here is the error message.
`PlatformException(200, Could not open browser, probably caused by unavailable custom tabs., null, null)`

My flutter doctor is following.

`[✓] Flutter (Channel stable, 2.5.1, on Mac OS X 10.14.6 18G9323 darwin-x64,
    locale ja-JP)
    • Flutter version 2.5.1 at /Users/s.imamura/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (2 weeks ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/s.imamura/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.60.2)
    • VS Code at /Users/s.imamura/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 94.0.4606.61`

Also, I am using twitter_login 4.0.1

Do you have any idea about how to get out from this error?

**Comment by ShotaImamura** [comment]
@0maru

**Comment by 0maru** [comment]
@ShotaImamura 
If you don't have chrome enabled, this may not work.
Please check your device settings.

**Comment by ShotaImamura** [comment]
That works, thank you so much. ( And sorry for forgetting to close.)
