### ISSUE TITLE
Error in login: 400, Failed to generate request token., Please check your APIKey or APISecret.

### ISSUE THREAD

**Issue by shawnlauzon** [0maru/twitter_login#66]
I'm failing attempting to login. I have confirmed that the api key and secret are correct by using [twurl](https://github.com/twitter/twurl) which does successfully log me in.

Failure is `PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)`

Code is simple:
```
final twitterLogin = TwitterLogin(
          apiKey: 'QW..Zt',
          apiSecretKey: 'pP..8h',
          redirectURI: 'leofinance://');

final authResult = await twitterLogin.login();
```

Authentication settings in Twitter dev console:
![image](https://user-images.githubusercontent.com/611529/140631385-5ed6a715-02fd-46c9-99bf-24a9b7686ae1.png)

This is happening on a real iOS device, `twitter_login: ^4.0.1`

**Comment by shawnlauzon** [comment]
I just saw that my redirect URI is different! Closing :/

**Comment by jessejay247** [comment]
I am seriously have this problem

**Comment by jaibyron** [comment]
@0maru - I was unable to run the example project and get the same error :

PlatformException(400, Failed to generate request token., Please check your APIKey or APISecret., null)

Can you please advise?
