### ISSUE TITLE
twitter api ver1.1 403 forbidden

### ISSUE THREAD

**Issue by r-kishimoto** [0maru/twitter_login#67]
Probably, API ver1.1 is not available when creating a new account in twitter developer from November 15, 2021.
Therefore, if you run getUserData(httpGet(ACCOUNT_VERIFY_URI,...)) will result in a 403 error.
You can use API version 1.1 by upgrading your account, but it would be great if you could add the process for API version 2.0!

**Comment by 0maru** [comment]
@r-kishimoto 
I thought I could use Twitter API ver 1.1.
This will be implemented at a higher priority.

**Comment by 0maru** [comment]
@r-kishimoto 
I have released v4.1.0-dev.
Twitter API v2.0 is now supported.
Please update this plugin.
