### ISSUE TITLE
How I can logout ?

### ISSUE THREAD

**Issue by AliYar-Khan** [0maru/twitter_login#68]
I am confused about log out ? Which class has the method of logout from twitter authentication ?

**Comment by 0maru** [comment]
@AliYar-Khan 
Twitter OAuth API doesn't expose the logout API, so it is impossible to implement.

Instead, you can use the force_login option to forces the user to enter their credentials to ensure the correct users account is authorized.
Can't the force_login option satisfy the requirement?

**Comment by AliYar-Khan** [comment]
How to logout the twitter after authentication in flutter app ?

**Comment by 0maru** [comment]
@AliYar-Khan 
Open Twitter in your browser and log out.

If you are using iPhone, use Safari.
If you are using Android, use chrome.
