### ISSUE TITLE
Login on Android hangs with "Redirecting back to the application"

### ISSUE THREAD

**Issue by shawnlauzon** [0maru/twitter_login#71]
I'm having a problem signing into Android. After displaying the authentication dialog and clicking the Authorize button, the "Redirecting you back to the application" screen is displayed. The circular indicator spins forever and never redirects my back to my application.

My same code is working good on iOS.

This seems similar to issue #69 , however the Developer account has been created for a number of months, and also I have tried both `login` and `loginV2` functions on both versions 4.0.1 and 4.1.0-dev, with the same results.

Both OAuth 1 and OAuth 2 have been enabled.
The redirects on in Twitter are set to `leofinance://` and `leomobile://`.
In my `app/src/main/AndroidManifest.xml`, I have:

```
<meta-data android:name="flutter_deeplinking_enabled" android:value="true" />            
<intent-filter android:autoVerify="true">
   <action android:name="android.intent.action.VIEW" />
   <category android:name="android.intent.category.DEFAULT" />
   <category android:name="android.intent.category.BROWSABLE" />
   <data android:scheme="http" android:host="leofinance.io" />
   <data android:scheme="https" />
   <data android:scheme="leofinance" />
</intent-filter>
```

shawn@MacBook-Pro ~ % flutter doctor -v
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-arm, locale en-US)
    • Flutter version 2.8.1 at /Users/shawn/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (4 days ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/shawn/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Users/shawn/Downloads/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/shawn/Downloads/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] VS Code (version 1.62.3)
    • VS Code at /Users/shawn/Downloads/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (3 available)
    • SM A025F (mobile)       • R9PR604VDCF                              • android-arm    • Android 11 (API 30)
    • Shawn’s iPhone (mobile) • 2e950c689065bc8c3604deb71d053816d35793ba • ios            • iOS 14.8.1 18H107
    • Chrome (web)            • chrome                                   • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

**Comment by zoylee-dev** [comment]
@shawnlauzon  Please try to upate your maniefest file like this

**Comment by zoylee-dev** [comment]
@shawnlauzon  can you help me how can I call loginV2 function because I am not able to call that function

**Comment by shawnlauzon** [comment]
Hi @zoylee-dev I already had all of that, except that the scheme I used was `leofinance` instead of `twittersdk` (but I forgot to include the `meta-data` field; I'll add that now). I tried changing it, but it fails, presumably because I still have set `leofinance://` as the redirect URL in the Twitter developers site. I'm fairly certain that changing it there is not going to resolve the issue.

As for calling loginV2, you need to first upgrade to the `4.1.0-dev` release, and then replace the call to `twitterLogin.login()` to `twitterLogin.loginV2()`.

**Comment by shawnlauzon** [comment]
I found the issue: I just needed to relaunch the Twitter app which was launched, and then the redirect worked fine :)

**Comment by firstep-official** [comment]
@shawnlauzon is it worked for you? i solved the return part but its returning null. wow the documentation here is so bad

**Comment by shawnlauzon** [comment]
@firstep-official yes it worked for me. I haven't looked at it since, so anything I know is in this issue. Hope it works out for you!
