### ISSUE TITLE
Exception: Exception: HttpException: Failed Forbidden

### ISSUE THREAD

**Issue by zoylee-dev** [0maru/twitter_login#72]
I am getting these exception even if I turn on api v2 in the developer console
Also I noticed one thing in your example that you are using loginv2 in main.dart in your example but I did not found this method in my example please help me where can I find that method

**Comment by 0maru** [comment]
@zoylee-dev 
Please update to v4.1.0-dev.
loginv2 is available in 4.1.0-dev.
