### ISSUE TITLE
Flutter For Web

### ISSUE THREAD

**Issue by shinriyo** [0maru/twitter_login#75]
Can you use it for the Web?

**Comment by 0maru** [comment]
@shinriyo 
Can't be used for Flutter for Web
I would like to support Flutter for Web, but it will take some time.

**Comment by shorben07** [comment]
@0maru I can make the contribution and implement web part(although I am a mobile developer) based on approach from the [article](https://itnext.io/flutter-web-oauth-authentication-through-external-window-d890a7ff6463)
The article is about Twitch and OAuth 2.0 but it could be easily rewritten to Twitter. What we really need from it is `Open an External Window` part and handling redirects. 
What do you think?

**Comment by 0maru** [comment]
@shorben07 
Please contribute if you can implement it according to Android and iOS processing.
I'll be waiting for Pull Requests.

Thank you.

**Comment by shorben07** [comment]
@0maru After doing more research it turned out that there is another plugin that already supports web https://pub.dev/packages/oauth2_client so, I withdraw my contribution commitment for now
