### ISSUE TITLE
The request token for this page is invalid. Using flutter and firebase

### ISSUE THREAD

**Issue by lorizz** [0maru/twitter_login#76]
Hello, I can't login with twitter.
I am using Flutter and Firebase, firebase has the right OAuth 1.0a keys, same in my TwitterLogin method, also the intent is correctly written passing the <package>:// format, enabled on authorized redirect on twitter dev.
What is happening? The error I am receiving is "AppAuth: No stored state - unable to handle response".

**Comment by 0maru** [comment]
@lorizz 
This plugins is not return "AppAuth: No stored state - unable to handle response".
Are you use Firebase instead of AppAuth?
