### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by ay-emma** [0maru/twitter_login#78]
Am using firebase Auth along with this package. I got a blank screen and no error to help me understand the problem. I am testing on an android 10 device.  
This happened when I call the TwitterLogin.login function, which then took me to a blank screen.
I would like to point out that I parsed the API keys and used the same call-back URL for the Twitter console, the XML file, and the dart file.

![twitter wahala](https://user-images.githubusercontent.com/47867546/151795223-d129e886-9c68-47aa-97a1-e256e5886def.png)

Am running on dart version ">=2.15.0-268.18.beta <3.0.0"
and flutter version 2.8.0-3.3.pre

**Comment by 0maru** [comment]
@ay-emma 
This plugin requires google chrome.
Can you please make sure that you have google chrome installed?

**Comment by ay-emma** [comment]
I am using chrome beta as my default browser (debugging on a physical device) . I will switch and get back to you shortly . Thanks for the quick response.

**Comment by ay-emma** [comment]
@0maru  it works, thanks 😊.  Does this mean the final APK release won't work on devices that do not have chrome installed.

**Comment by 0maru** [comment]
@ay-emma 
Yes.
This plugin requires chrome.

It is used with chrome custom tabs.

**Comment by ay-emma** [comment]
@0maru I would like to suggest that the limitations should be added to the documention.
