### ISSUE TITLE
Blurry thumbnail image

### ISSUE THREAD

**Issue by gtu-myowin** [0maru/twitter_login#79]
After reading the twitter [api docs](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners) and learning this package, I realized that this package doesn't provide multiple profile photo size. But since the only difference in normal (48x48) and the original large image is the word "_normal" in file name. 

I am using replace function to get large image

```dart
String? url = authResult.user?.thumbnailImage.replaceFirst('_normal', '');
```

Will you modify the code so that developer can get different thumbnail sizes?

**Comment by Clashkid155** [comment]
@0maru This doesn't seem to be implemented.
