### ISSUE TITLE
Twitter call back uri

### ISSUE THREAD

**Issue by CarrynWKerr** [0maru/twitter_login#83]
In the documentation, it says to use the app name as the callback uri, i.e. in the manifest scheme app_name and in the callback in the code app_name:// 

In Twitter, it does not allow underscores. I'm not sure if this is a new thing, but I can't seem to get the login working.

**Comment by mashegoindustries** [comment]
What what that really means is

if your app name is instagram, then your call back is instagram://

DO NOT USE CALL BACK URL FROM FIREBASE


Please note that 'android:scheme' below is also set to instagram://

<intent-filter>
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                
                
                <data android:scheme="instagram://" /> 
            </intent-filter>





FINAL STEP
Inside twitter developer website, make sure that you paste the very same 'instagram://' DO NOT PASTE FIREBASE CALL BACK URL

Callback URI / Redirect URL
instagram://

**Comment by CarrynWKerr** [comment]
> What what that really means is
> 
> if your app name is instagram, then your call back is instagram://
> 
> DO NOT USE CALL BACK URL FROM FIREBASE
> 
> Please note that 'android:scheme' below is also set to instagram://
> 
> FINAL STEP Inside twitter developer website, make sure that you paste the very same 'instagram://' DO NOT PASTE FIREBASE CALL BACK URL
> 
> Callback URI / Redirect URL instagram://

Thanks so much! What if the app name is, for example, instagram_app? I think this is where my problem lies (the underscore). I've followed the steps in the video, but that allows an underscore in the Twitter callback URL.
