### ISSUE TITLE
Not able to get email id in twitter.

### ISSUE THREAD

**Issue by vishwesh-aubergine** [0maru/twitter_login#9]
I have used this package to authenticate with Twitter 
I have enabled mark in the Twitter application to get emails.
```
Future<UserCredential> signInWithTwitter() async {
    // Create a TwitterLogin instance
    final TwitterLogin twitterLogin = new TwitterLogin(
        apiKey: '',
        apiSecretKey: '',
        redirectURI: '//');

    // Trigger the sign-in flow
    // final TwitterLoginResult loginResult = await twitterLogin.authorize();
    //
    // // Get the Logged In session
    // final TwitterSession twitterSession = loginResult.session;

    // Create a credential from the access token\
    final authResult = await twitterLogin.login();

    switch (authResult.status) {
      case TwitterLoginStatus.loggedIn:
        // success
        final AuthCredential twitterAuthCredential =
            TwitterAuthProvider.credential(
                accessToken: authResult.authToken,
                secret: authResult.authTokenSecret);
          // Once signed in, return the UserCredential
        return await FirebaseAuth.instance
            .signInWithCredential(twitterAuthCredential);
        break;
      case TwitterLoginStatus.cancelledByUser:
        throw SignInCancelledException(
            null, "Account exist with different authentication provider.");
        break;
      case TwitterLoginStatus.error:
        throw SignInCancelledException(
            null, "Twitter Authentication Not Performed");
        break;
    }
  }
```

**Comment by 0maru** [comment]
This plugin is currently not able to retrieve email addresses.
However, there was a way to get an email address, so I'll add a feature to it.

It should work fine for Firebase SignIn, so please wait a while.

**Comment by vishwesh-aubergine** [comment]
Thanks for looking into it.
Waiting for your solution to integrate..... :)

**Comment by bounty1342** [comment]
hi,

If you can't wait, you can call this API below, anyway user could be null so wonder how this will match with firebase.

https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials

Also waiting for this :)

**Comment by 0maru** [comment]
@vishwesh-aubergine 
I added the ability to get email address, username and profile picture.
please update package to v2.1.0.
You can get the email address without changing the logic.

For example
```
final result = await twitterLogin.login();
final email = result.user.email; // user email address
final email = result.user.thumbnailImage; // user setting picture
final email = result.user.name; // user name
final email = result.user.screenName; // twitter account id
```

**Comment by nayanAubie** [comment]
This issue is present in the latest version `twitter_login: ^4.2.3`
I enabled email permissions from the **Twitter developer console**
<img width="712" alt="Screenshot 2022-11-11 at 12 50 09 PM" src="https://user-images.githubusercontent.com/109264909/201287784-0c707723-495a-4643-b035-e61b55e114c5.png">
![Simulator Screen Shot - iPhone 14 - 2022-11-11 at 12 37 05](https://user-images.githubusercontent.com/109264909/201288092-166dff8e-37cc-46b4-8040-7eaaf176af11.png)

**Comment by nayanAubie** [comment]
@0maru please check above issue

**Comment by 0maru** [comment]
@nayanAubie 
In example project I was able to get emails.

Do you have an email address set up for your Twitter account?

**Comment by nayanAubie** [comment]
@0maru That's what I've shared in the above image.
`Request email from users` is enabled.
And in your current code, I see the `email` field is deprecated.

[See your code here](https://github.com/0maru/twitter_login/blob/8901cc183deba7f769d022e3860a947c0840f724/lib/entity/user.dart#L42)

- You mentioned that `Discontinue if Twitter API v2 does not provide a way to get an email.`
- But as per my understanding, something to be there from Twitter to grab an email address.

**Comment by 0maru** [comment]
@nayanAubie 
Yes, email field is deprecated because it cannot be retrieved with Twitter API v2.
Email field is left as it can be retrieved using Twitter API v1.1.

If you login using `login()` method, Twitter API v1.1 is used so you can get email field.
Example code is written in the [README](https://github.com/0maru/twitter_login#example).

If you cannot get email field using `login()` method, please create another PR with the details.

**Comment by nayanAubie** [comment]
@0maru Can you please provide any official documentation reference where Twitter has mentioned that you can't grab email from V2 APIs?

**Comment by 0maru** [comment]
@nayanAubie 
There is no documentation stating that email can no longer be retrieved.
However, there is documentation that clearly states that there are plans to replacement the api v2.
https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map

![2022-11-21_23_00_40](https://user-images.githubusercontent.com/43493921/203075012-db69fbf9-9a1c-43fc-80b2-45dbd88cb47c.png)
