### ISSUE TITLE
Login oAuth v1.0a returns Forbidden

### ISSUE THREAD

**Issue by malbadawi** [0maru/twitter_login#91]
```
Future<Map<String, dynamic>> httpGet(
  String url, {
  Map<String, dynamic>? query,
  required Map<String, dynamic> authHeader,
  required String apiKey,
  required String apiSecretKey,
  required String tokenSecret,
}) async {
  try {
    final _signature = Signature(
      url: url,
      method: 'GET',
      params: authHeader,
      apiKey: apiKey,
      apiSecretKey: apiSecretKey,
      tokenSecretKey: tokenSecret,
    );
    authHeader['oauth_signature'] = _signature.signatureHmacSha1();
    final header = generateAuthHeader(authHeader);
    final http.Client _httpClient = http.Client();
    final _url = Uri.parse(url).replace(queryParameters: query);
    final http.Response res = await _httpClient.get(
      _url,
      headers: <String, String>{'Authorization': header!},
    );
    if (res.statusCode != 200) {
      throw HttpException("Failed ${res.reasonPhrase}");
    }

    return jsonDecode(res.body);
  } on Exception {
    rethrow;
  }
}
```

final http.Response res = await _httpClient.get(
      _url,
      headers: <String, String>{'Authorization': header!},
    );

always returns 
request = {Request} GET https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true
statusCode = 403
**reasonPhrase = "Forbidden"**
contentLength = 360
headers = {_InternalLinkedHashMap} size = 8
isRedirect = false
persistentConnection = true
bodyBytes = {_Uint8List} size = 360

and I'm calling this function like 

final authResult = await twitterLogin.login();

on the contrary I've called 
final authResult = await twitterLogin.loginV2();

and it does not return an email address always so I wonder how can I call the following API endpoint

https://api.twitter.com/1.1/account/verify_credentials.json?include_email=true

using twitter_login: 4.1.0?

**Comment by 0maru** [comment]
@malbadawi 
Does your Twitter App support API v1 or API v2?
If v1 is supported, use the login method.
If v1 is not supported, use the loginV2 method.

Cannot be called `1.1/account/verify_credentials.json` outside of the login process.
Also, Twitter API V2 does not provide a way to retrieve email addresses.
